version: "3"

services:
    catalog:
      build:
        context: ./catalog
        dockerfile: Dockerfile
      ports:
        - 8080:8080
      networks: 
            - net
    inventory:
      build:
        context: ./inventory
        dockerfile: Dockerfile
      ports:
         - 8081:8081
      networks:
            - net
    pricing:
      build:
        context: ./pricing
        dockerfile: Dockerfile
      ports:
         - 8082:8082
      networks: 
            - net
    mongodb:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db
      networks:
            - net
volumes:
    mongodb_data_container:
networks:
    net:
