apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: inventory-depl
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventoryservice
        image: inventoryservice:1.0
        ports:
        - containerPort: 8081
---  
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002