apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pricing-depl
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pricing
    spec:
      containers:
      - name: pricingservice
        image: pricingservice:1.0
        ports:
        - containerPort: 8081
---  
apiVersion: v1
kind: Service
metadata:
  name: pricing-service
spec:
  selector:
    app: pricing
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30003